"""create milkTeas table

Revision ID: 428610b8f00c
Revises: d3221ad4c6b8
Create Date: 2024-11-12 17:39:31.392844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428610b8f00c'
down_revision = 'd3221ad4c6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tea_Items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tea_Items'))
    )
    op.create_table('milk_teas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tea_item_id', sa.Integer(), nullable=True),
    sa.Column('boba_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['boba_id'], ['bobas.id'], name=op.f('fk_milk_teas_boba_id_bobas')),
    sa.ForeignKeyConstraint(['tea_item_id'], ['tea_Items.id'], name=op.f('fk_milk_teas_tea_item_id_tea_Items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milk_teas'))
    )
    op.drop_table('teaItems')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teaItems',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('milk_teas')
    op.drop_table('tea_Items')
    # ### end Alembic commands ###
