"""Create boba table

Revision ID: 978aea2a9584
Revises: 178c8337256c
Create Date: 2024-11-12 15:40:23.123039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978aea2a9584'
down_revision = '178c8337256c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bobas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bobas'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bobas')
    # ### end Alembic commands ###
