"""create teaItem

Revision ID: d3221ad4c6b8
Revises: 978aea2a9584
Create Date: 2024-11-12 16:11:24.982730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3221ad4c6b8'
down_revision = '978aea2a9584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teaItems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teaItems'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teaItems')
    # ### end Alembic commands ###
